# Makefile
CCPP = g++ -Wall -std=c++17

cw01_02: cw01_02.cpp
	$(CCPP) cw01_02.cpp -o cw01_02

cw03: cw03.cpp
	$(CCPP) cw03.cpp -o cw03

cw04: cw04.cpp
	$(CCPP) cw04.cpp -o cw04

cw05: cw05.cpp
	$(CCPP) cw05.cpp -o cw05

clean:
	rm -f cw01_02
	rm -f cw03
	rm -f cw04
